import './globals.css'
import { Inter } from 'next/font/google'

import { ApolloProvider } from '@apollo/client';
import { HttpLink } from '@apollo/client/link/http';
import { ApolloClient, InMemoryCache } from '@apollo/client';

const httpLink = new HttpLink({
  uri: 'http://localhost:3000/graphql',
});
const client = new ApolloClient({
  link: httpLink,
  cache: new InMemoryCache(),
});

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ApolloProvider client={client}>
      <html lang="ja">
        <body className={inter.className}>{children}</body>
      </html>
    </ApolloProvider>
  )
}
